apiVersion: v1
kind: Pod
metadata:
  name: zipkin-ui
  namespace: otlp-demo
spec:
  containers:
  - name: zipkin
    image: openzipkin/zipkin
    ports:
    - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  type: LoadBalancer
  ports:
  - port: 9411
    targetPort: 9411
    protocol: TCP